Js suggested app structure
tests-always-included/style-guide pull request #14
Opened 2017-01-19 19:05 UTC by kyle-long

2017-01-19 20:13 UTC, quantumew approved these changes

2017-01-20 01:21 UTC, AbsentSemicolon requested changes

2017-01-20 01:21 UTC, AbsentSemicolon commented on lang/js/suggested-app-structure.md
> +The below is an example application structure. This application uses HTTP as a communication layer but it would work equally well with other communication types.
Don't need `The` at the beginning of the sentence.

Maybe put `example` instead of `application` in the second sentence.

2017-01-20 01:21 UTC, AbsentSemicolon commented on lang/js/suggested-app-structure.md
> +* `bin` - Executable files. These deal with a command line interface as the communication layer. If the executable must use something in another communication layer (for example starting a server for
Command Line Interface should be capitalized and put (CLI) afterwards, just in case you use CLI later on.

2017-01-20 14:47 UTC, kyle-long commented on lang/js/suggested-app-structure.md
> +The below is an example application structure. This application uses HTTP as a communication layer but it would work equally well with other communication types.
b2ee2a5233c859282340e4c3694b61f20e16ee02

2017-01-20 14:47 UTC, kyle-long commented on lang/js/suggested-app-structure.md
> +* `bin` - Executable files. These deal with a command line interface as the communication layer. If the executable must use something in another communication layer (for example starting a server for
b2ee2a5233c859282340e4c3694b61f20e16ee02

2017-01-20 15:34 UTC, AbsentSemicolon approved these changes

2017-01-20 16:18 UTC, merged