Add SQL style guide
tests-always-included/style-guide pull request #4
Opened 2016-10-20 17:30 UTC by lnagle93

2016-10-20 17:44 UTC, fidian requested changes
Do queries start on their own line?  Do they have a trailing newline?  For instance, what would happen to the queries that you've embedded?  I think I would prefer that they are offset from non-SQL code.  Your thoughts?  Thoughts of the others?

```
return db->query("
    SELECT *
    FROM theTable
");
```

2016-10-20 17:44 UTC, fidian commented on lang/sql/index.md
> +pageid: lang-sql
The yaml frontmatter needs a line of hyphens after it, just like the first line.

2016-10-20 17:44 UTC, fidian commented on lang/sql/index.md
> +    ORDER BY ASC
You need to have a field name before ASC.

2016-10-20 17:44 UTC, fidian commented on lang/sql/index.md
> +    WHERE DATEDIFF(NOW(), someTable.timeStamp)
For a more brief example, I would omit `someTable.` from this line.

2016-10-20 17:44 UTC, fidian commented on lang/sql/index.md
> +    FROM someTable
Add the AS here.

    FROM someTable as st

2016-10-20 17:44 UTC, fidian commented on lang/sql/index.md
> +    WHERE column IN config.columns
config.columns is not valid for this example.  

    WHERE column IN ("column1", "column2")

2016-10-20 17:44 UTC, fidian commented on lang/sql/index.md
> +The above rules apply for all subqueries as well.
Add a note about subqueries starting on a new line and also being indented further.

2016-10-20 17:44 UTC, fidian commented on lang/sql/index.md
> +        SELECT someTable.id AS someAlias, someTable.exampleColumn
Unless you're joining, having the table name before the fields only adds to the amount of data that you need to process.  Simpler SQL queries are better.

2016-10-20 17:52 UTC, AbsentSemicolon commented on lang/sql/index.md
> +When SELECTing multiple columns, and place on the same line.
I don't like laying things like this. Should just say "selecting".

2016-10-20 17:52 UTC, AbsentSemicolon commented on lang/sql/index.md
> +AND should be dropped onto a newline and given an additional indentation of four spaces relative to the clause it's a part of.
Same as above, I wouldn't call out what it is with it in all caps.

2016-10-20 17:59 UTC, lnagle93 commented on lang/sql/index.md
> +When SELECTing multiple columns, and place on the same line.
I agree with the quotes, but I think it should remain capitalized, as that is how it is used.

2016-10-20 18:04 UTC, lnagle93 commented on lang/sql/index.md
> +        SELECT someTable.id AS someAlias, someTable.exampleColumn
Fixed.

2016-10-20 18:04 UTC, lnagle commented on lang/sql/index.md
> +The above rules apply for all subqueries as well.
Added.

2016-10-20 18:04 UTC, lnagle commented on lang/sql/index.md
> +    WHERE column IN config.columns
Fixed.

2016-10-20 18:04 UTC, lnagle93 commented on lang/sql/index.md
> +    FROM someTable
Fixed.

2016-10-20 18:04 UTC, lnagle93 commented on lang/sql/index.md
> +    ORDER BY ASC
Fixed.

2016-10-20 18:04 UTC, lnagle93 commented on lang/sql/index.md
> +pageid: lang-sql
Fixed.

2016-10-20 18:05 UTC, lnagle93 commented
Added an example for SQL queries embedded in code to this upcoming

2016-10-20 18:17 UTC, AbsentSemicolon commented on lang/sql/index.md
>  IN, AS, and OR should all be placed on the same line as the clause they are a part of.
These should be quoted as well, thought you'd see these too, but I should have called them out.

2016-10-20 18:20 UTC, fidian commented on lang/sql/index.md
> +pageid: lang-sql
The keywords are missing.  Run `bin/update-all-keywords`

2016-10-20 18:22 UTC, fidian requested changes
Couple more things.

2016-10-20 18:22 UTC, fidian commented on lang/sql/index.md
> +    WHERE DATEDIFF(NOW(), someTable.timeStamp)
Missing `FROM someTable` and I suggest removing `someTable.` from this line.

2016-10-20 18:22 UTC, fidian commented on lang/sql/index.md
> +    ORDER BY DESC
Missing a field before `DESC`.

2016-10-20 18:22 UTC, fidian commented on lang/sql/index.md
> +When using "SELECT" on multiple columns, place the columns on the same line.
I think backticks are more appropriate for quotes here and for the next paragraph.  You're citing the code.

2016-10-20 18:22 UTC, fidian commented on lang/sql/index.md
> +IN, AS, and OR should all be placed on the same line as the clause they are a part of.
These should also be surrounded with quotes or backticks.

2016-10-20 21:02 UTC, lnagle commented on lang/sql/index.md
> +    WHERE DATEDIFF(NOW(), someTable.timeStamp)
Fixed.

2016-10-20 21:02 UTC, lnagle93 commented on lang/sql/index.md
> +When using "SELECT" on multiple columns, place the columns on the same line.
Agreed, and changed.

2016-10-20 21:02 UTC, lnagle commented on lang/sql/index.md
> +IN, AS, and OR should all be placed on the same line as the clause they are a part of.
Changed.

2016-10-20 21:02 UTC, lnagle93 commented on lang/sql/index.md
> +    ORDER BY DESC
Fixed.

2016-10-21 13:43 UTC, lnagle93 commented on lang/sql/index.md
> +pageid: lang-sql
My version of BSD version of sed doesn't play nice with that script, and I'm not having much luck troubleshooting D:

2016-10-21 14:08 UTC, lnagle93 commented on lang/sql/index.md
> +pageid: lang-sql
Nevermind, Derek and I made it work. Fixed.

2016-10-21 14:57 UTC, fidian approved these changes

2016-10-21 16:32 UTC, AbsentSemicolon commented
Reviewed and looks good to me.

2016-10-21 16:34 UTC, merged